package fr.factionbedrock.aerialhell.Client;

import com.google.common.base.Supplier;

import fr.factionbedrock.aerialhell.Client.Gui.Screen.Inventory.*;
import fr.factionbedrock.aerialhell.Registry.AerialHellBlocksAndItems;
import fr.factionbedrock.aerialhell.Registry.AerialHellMenuTypes;
import net.minecraft.client.gui.screens.MenuScreens;
import net.minecraft.client.renderer.ItemBlockRenderTypes;
import net.minecraft.world.level.block.Block;
import net.minecraft.client.renderer.RenderType;

public class AerialHellRendering
{
	public static void registerBlockRenderLayers()
	{
		RenderType translucent = RenderType.translucent();
		RenderType cutout = RenderType.cutout();
		RenderType cutout_mipped = RenderType.cutoutMipped();
		
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_PLANKS.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_LOG.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_SLAB.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_STAIRS.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_FENCE.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_GATE.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_DOOR.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_TRAPDOOR.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_WOOL.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_RUBY_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_FLUORITE_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_BARREL.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GHOST_BOAT_CRAFTING_TABLE.get(), translucent);
		render(() -> AerialHellBlocksAndItems.WHITE_SOLID_ETHER.get(), translucent);
		render(() -> AerialHellBlocksAndItems.BLUE_SOLID_ETHER.get(), translucent);
		render(() -> AerialHellBlocksAndItems.CRYSTAL_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.STELLAR_STONE_CRYSTAL_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.SHADOW_CRYSTAL_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.SHADOW_CRYSTAL_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.CRYSTALLIZED_LEAVES.get(), translucent);
		render(() -> AerialHellBlocksAndItems.CRYSTALLIZED_FIRE.get(), cutout);
		render(() -> AerialHellBlocksAndItems.GOLDEN_SOLID_ETHER.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GREEN_SOLID_ETHER.get(), translucent);
		render(() -> AerialHellBlocksAndItems.PURPLE_SOLID_ETHER.get(), translucent);
        render(() -> AerialHellBlocksAndItems.GLOWING_STICK_FRUIT_VINES.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GLOWING_STICK_FRUIT_VINES_PLANT.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BLOSSOMING_VINES.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BLOSSOMING_VINES_PLANT.get(), cutout);
        render(() -> AerialHellBlocksAndItems.CLIMBING_VINE.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_SUGAR_CANE.get(), cutout);
        render(() -> AerialHellBlocksAndItems.FULL_MOON_FLOWER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.LAZULI_ROOTS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.LAZULI_ROOTS_PLANT.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_ROOTS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_ROOTS_PLANT.get(), cutout);
        render(() -> AerialHellBlocksAndItems.DEAD_ROOTS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.DEAD_ROOTS_PLANT.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GLOWING_ROOTS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GLOWING_ROOTS_PLANT.get(), cutout);
		render(() -> AerialHellBlocksAndItems.AERIAL_BERRY_BUSH.get(), cutout);
		render(() -> AerialHellBlocksAndItems.VIBRANT_AERIAL_BERRY_BUSH.get(), cutout);
		render(() -> AerialHellBlocksAndItems.STELLAR_WHEAT.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BLUE_FLOWER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BLACK_ROSE.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BELLFLOWER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_STONE.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_COBBLESTONE.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_STONE_SLAB.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_COBBLESTONE_SLAB.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_STONE_STAIRS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_COBBLESTONE_STAIRS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_STONE_WALL.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MOSSY_STELLAR_COBBLESTONE_WALL.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_MUD_BRICKS.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_SHADOW_CATACOMBS_BRICKS.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_MUD_BRICKS_SLAB.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_MUD_BRICKS_STAIRS.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_MUD_BRICKS_WALL.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_SHADOW_CATACOMBS_BRICKS_SLAB.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_SHADOW_CATACOMBS_BRICKS_STAIRS.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MOSSY_SHADOW_CATACOMBS_BRICKS_WALL.get(), cutout);
		render(() -> AerialHellBlocksAndItems.MUD_GLYPH_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.LUNATIC_GLYPH_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.GOLDEN_NETHER_PRISON_GLYPH_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.VOLUCITE_GLYPH_BLOCK.get(), translucent);
		render(() -> AerialHellBlocksAndItems.SHADOW_CATACOMBS_GLYPH_BLOCK.get(), translucent);
        render(() -> AerialHellBlocksAndItems.STELLAR_GRASS_BLOCK.get(), cutout_mipped);
        render(() -> AerialHellBlocksAndItems.STELLAR_PODZOL.get(), cutout_mipped);
        render(() -> AerialHellBlocksAndItems.CHISELED_STELLAR_GRASS_BLOCK.get(), cutout_mipped);
        render(() -> AerialHellBlocksAndItems.SHADOW_GRASS_BLOCK.get(), cutout_mipped);
        render(() -> AerialHellBlocksAndItems.STELLAR_GRASS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_GRASS_BALL.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BRAMBLES.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SHADOW_BRAMBLES.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SHADOW_GRASS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SHADOW_GRASS_BALL.get(), cutout);
        render(() -> AerialHellBlocksAndItems.PURPLISH_STELLAR_GRASS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_CLOVERS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GLOWING_STELLAR_GRASS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.THORNY_COBWEB.get(), cutout);
        render(() -> AerialHellBlocksAndItems.AERIAL_TREE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GOLDEN_BEECH_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.COPPER_PINE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.LAPIS_ROBINIA_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SHADOW_PINE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_JUNGLE_TREE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.PURPLE_SHADOW_PINE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.CORTINARIUS_VIOLACEUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.VERDIGRIS_AGARIC.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GLOWING_BOLETUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.TALL_GLOWING_BOLETUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BLUE_MEANIE_CLUSTER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GIANT_ROOT_SHROOM.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_TALL_GRASS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_TALL_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_VERY_TALL_GRASS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.BLUISH_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.TALL_BLUISH_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POLYCHROME_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.TALL_POLYCHROME_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.STELLAR_DEAD_BUSH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_BLUE_FLOWER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_BLACK_ROSE.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_BELLFLOWER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_STELLAR_FERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_STELLAR_DEAD_BUSH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_SKY_CACTUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_VIBRANT_SKY_CACTUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_AERIAL_TREE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_GOLDEN_BEECH_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_COPPER_PINE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_LAPIS_ROBINIA_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_SHADOW_PINE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_PURPLE_SHADOW_PINE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_STELLAR_JUNGLE_TREE_SAPLING.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_CORTINARIUS_VIOLACEUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_VERDIGRIS_AGARIC.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_VINE_BLOSSOM.get(), cutout);
        render(() -> AerialHellBlocksAndItems.POTTED_GLOWING_BOLETUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.AERIAL_HELL_PORTAL.get(), translucent);
        render(() -> AerialHellBlocksAndItems.SLIPPERY_SAND_GLASS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.RED_SLIPPERY_SAND_GLASS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.BLACK_SLIPPERY_SAND_GLASS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.BLUE_SLIPPERY_SAND_GLASS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.GREEN_SLIPPERY_SAND_GLASS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.SLIPPERY_SAND_GLASS_PANE.get(), translucent);
        render(() -> AerialHellBlocksAndItems.RED_SLIPPERY_SAND_GLASS_PANE.get(), translucent);
        render(() -> AerialHellBlocksAndItems.BLACK_SLIPPERY_SAND_GLASS_PANE.get(), translucent);
        render(() -> AerialHellBlocksAndItems.BLUE_SLIPPERY_SAND_GLASS_PANE.get(), translucent);
        render(() -> AerialHellBlocksAndItems.GREEN_SLIPPERY_SAND_GLASS_PANE.get(), translucent);
        render(() -> AerialHellBlocksAndItems.MAGMATIC_GEL_BLOCK.get(), translucent);
        render(() -> AerialHellBlocksAndItems.MAGMATIC_GEL_SLAB.get(), translucent);
        render(() -> AerialHellBlocksAndItems.MAGMATIC_GEL_STAIRS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.MAGMATIC_GEL_WALL.get(), translucent);
        render(() -> AerialHellBlocksAndItems.AERIAL_TREE_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GOLDEN_BEECH_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.COPPER_PINE_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.LAPIS_ROBINIA_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SHADOW_PINE_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SKY_CACTUS_FIBER_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.GRAY_SHROOM_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.RUBY_DOOR.get(), cutout);
        render(() -> AerialHellBlocksAndItems.AERIAL_TREE_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.LAPIS_ROBINIA_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.GOLDEN_BEECH_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.COPPER_PINE_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.SHADOW_PINE_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.SKY_CACTUS_FIBER_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.GRAY_SHROOM_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.RUBY_TRAPDOOR.get(), translucent);
        render(() -> AerialHellBlocksAndItems.RUBY_BARS.get(), translucent);
		render(() -> AerialHellBlocksAndItems.SHADOW_BARS.get(), translucent);
        render(() -> AerialHellBlocksAndItems.SKY_CACTUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.VIBRANT_SKY_CACTUS.get(), cutout);
        render(() -> AerialHellBlocksAndItems.FLUORITE_TORCH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.FLUORITE_WALL_TORCH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.RUBY_LANTERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.RUBY_FLUORITE_LANTERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.VOLUCITE_LANTERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.VOLUCITE_FLUORITE_LANTERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.FLUORITE_LANTERN.get(), cutout);
        render(() -> AerialHellBlocksAndItems.LUNATIC_LANTERN.get(), cutout);
		render(() -> AerialHellBlocksAndItems.SHADOW_LANTERN.get(), cutout);
		render(() -> AerialHellBlocksAndItems.RUBY_CHAIN.get(), cutout_mipped);
		render(() -> AerialHellBlocksAndItems.VOLUCITE_CHAIN.get(), cutout_mipped);
		render(() -> AerialHellBlocksAndItems.LUNATIC_CHAIN.get(), cutout_mipped);
		render(() -> AerialHellBlocksAndItems.SHADOW_CHAIN.get(), cutout_mipped);
		render(() -> AerialHellBlocksAndItems.SHADOW_TORCH.get(), cutout);
		render(() -> AerialHellBlocksAndItems.SHADOW_WALL_TORCH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.VOLUCITE_TORCH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.VOLUCITE_WALL_TORCH.get(), cutout);
        render(() -> AerialHellBlocksAndItems.SKY_LADDER.get(), cutout);
        render(() -> AerialHellBlocksAndItems.MUD_CYCLE_MAGE_TROPHY.get(), cutout);
        render(() -> AerialHellBlocksAndItems.CHAINED_GOD_TROPHY.get(), cutout);
	}
	
	private static void render(Supplier<? extends Block> block, RenderType render)
	{
        ItemBlockRenderTypes.setRenderLayer(block.get(), render);
    }
	
	public static void registerScreensMenus()
	{
        MenuScreens.register(AerialHellMenuTypes.OSCILLATOR.get(), OscillatorScreen::new);
        MenuScreens.register(AerialHellMenuTypes.FREEZER.get(), FreezerScreen::new);
        MenuScreens.register(AerialHellMenuTypes.STELLAR_FURNACE.get(), StellarFurnaceScreen::new);
    }
}
